name: Deploy RevoShelf Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}

          script: |
            set -e
            export HOME=/home/turab
            export GIT_SSH_COMMAND="ssh -F /home/turab/.ssh/config"
            cd /var/www/revoshelf/campus_be

            git fetch origin
            git reset --hard origin/main

            npm ci

            pm2 restart revoshelf-backend

            pm2 save
